INSERT INTO product (product_name, description) VALUES ('t-shirt', 't-shirt description');
INSERT INTO product (product_name, description) VALUES ('polo shirt', 'polo shirt description');
INSERT INTO product (product_name, description) VALUES ('Sweat shirt', 'Sweat shirt description');
INSERT INTO product (product_name, description) VALUES ('Long shirt', 'Long shirt description');
INSERT INTO product (product_name, description) VALUES ('Short shirt', 'Short shirt description');
INSERT INTO product (product_name, description) VALUES ('Large shirt', 'Large shirt description');
INSERT INTO product (product_name, description) VALUES ('XL shirt', 'XL shirt description');
INSERT INTO product (product_name, description) VALUES ('Small shirt', 'Small shirt description');
INSERT INTO product (product_name, description) VALUES ('Double shirt', 'Double shirt description');
INSERT INTO product (product_name, description) VALUES ('shirt shirt', 'shirt shirt description');
